#pragma once
#include "CoreMinimal.h"
#include "EAreaInfoTweakCheckType.generated.h"

UENUM(BlueprintType)
enum class EAreaInfoTweakCheckType : uint8 {
    PROGRESS,
    FLAG_BOOL,
    FLAG_NUM,
    ITEM_NUM,
    FUNCTION,
    KIZUNA_PROGRESS_Y_KASANE,
    KIZUNA_PROGRESS_Y_HANABI,
    KIZUNA_PROGRESS_Y_GENMA,
    KIZUNA_PROGRESS_Y_TSUGUMI,
    KIZUNA_PROGRESS_Y_LUKA,
    KIZUNA_PROGRESS_Y_KAGEROU,
    KIZUNA_PROGRESS_Y_SHIDEN,
    KIZUNA_PROGRESS_Y_KYOUKA,
    KIZUNA_PROGRESS_Y_ARASHI,
    KIZUNA_PROGRESS_K_YUITO,
    KIZUNA_PROGRESS_K_HANABI,
    KIZUNA_PROGRESS_K_GENMA,
    KIZUNA_PROGRESS_K_TSUGUMI,
    KIZUNA_PROGRESS_K_LUKA,
    KIZUNA_PROGRESS_K_KAGEROU,
    KIZUNA_PROGRESS_K_SHIDEN,
    KIZUNA_PROGRESS_K_KYOUKA,
    KIZUNA_PROGRESS_K_ARASHI,
    PLAYER_IS_YUITO,
    PLAYER_IS_KASANE,
    NUM,
};

