#pragma once
#include "CoreMinimal.h"
#include "EBrainTalkGimmickCondition.generated.h"

UENUM(BlueprintType)
enum class EBrainTalkGimmickCondition : uint8 {
    BrainTalkGimmick_0,
    BrainTalkGimmick_1,
    BrainTalkGimmick_2,
    BrainTalkGimmick_3,
    BrainTalkGimmick_4,
    BrainTalkGimmick_5,
    BrainTalkGimmick_6,
    BrainTalkGimmick_7,
    BrainTalkGimmick_8,
    BrainTalkGimmick_9,
    BrainTalkGimmick_10,
    BrainTalkGimmick_11,
    BrainTalkGimmick_12,
    BrainTalkGimmick_13,
    BrainTalkGimmick_14,
    BrainTalkGimmick_15,
    BrainTalkGimmick_16,
    BrainTalkGimmick_17,
    BrainTalkGimmick_18,
    BrainTalkGimmick_19,
    BrainTalkGimmick_20,
    BrainTalkGimmick_21,
    BrainTalkGimmick_22,
    BrainTalkGimmick_23,
    BrainTalkGimmick_24,
    BrainTalkGimmick_25,
    BrainTalkGimmick_26,
    BrainTalkGimmick_27,
    BrainTalkGimmick_28,
    BrainTalkGimmick_29,
    BrainTalkGimmick_30,
    BrainTalkGimmick_31,
    BrainTalkGimmick_32,
    BrainTalkGimmick_33,
    BrainTalkGimmick_34,
    BrainTalkGimmick_35,
    Max,
};

