#pragma once
#include "CoreMinimal.h"
#include "EEventWaitMode.generated.h"

UENUM(BlueprintType)
enum class EEventWaitMode : uint8 {
    None,
    Timer,
    Message,
    GeneralChoice,
    Input,
    EndMotion,
    DynamicCutscene,
    PostProcessSequencer,
    PresentSequencer,
    AnimMontage,
    LoadAsset,
    LoadAssetAll,
    Fade,
    Shop,
    SaveLoad,
    LoadChangeScene,
    BrainField,
    BrainFieldTuto,
    SubQuestReward,
    PhaseAnimation,
    NewStaticInGeneralAnimation,
    TutoTips,
    TutoOperationTips,
    SequencerCapture,
    SequencerCaptureBG,
    EndSubMenu,
    EndBrainTalk,
    EndPrepareMovie,
    CharacterEventMoveEnd,
    SkipEvent,
    WaitBrainFieldButton,
    WaitSASCutinExtra,
    WaitEventTips,
    WaitCreditEvent,
    WaitLoadMakeEventAsset,
    WaitSASCutinCh0500_0700,
    WaitSASCutinCH0400_0600,
    WaitLogMessage,
    WaitSasWindow,
    WaitBrainFieldDangerLV,
    WaitMipLoadReady,
    WaitMipLoadReadyMesh,
    WaitCloseSystemMessage,
    EndCode,
    EndKeyword,
    EndVisionSimulatorSelect,
};

