#pragma once
#include "CoreMinimal.h"
#include "EItemIcon.generated.h"

UENUM(BlueprintType)
enum class EItemIcon : uint8 {
    NONE,
    CURE_S_SOLO,
    CURE_S_PARTY,
    CURE_M_SOLO,
    CURE_M_PARTY,
    CURE_L_SOLO,
    CURE_L_PARTY,
    MEDICINE_SOLO,
    MEDICINE_PARTY,
    BRAIN_GAUGE_FULL,
    SAS_GAUGE_FULL,
    SPECIAL_OBJECT_TELEPORT_KEY,
    AGITATION,
    KEY_ITEM,
    MATERIAL_0000,
    MATERIAL_1000,
    WEAPON_SWORD,
    WEAPON_THROWING_KNIFE,
    WEAPON_TORCH,
    WEAPON_GLOBE,
    WEAPON_REVOLVER,
    WEAPON_HAMMER,
    WEAPON_KNIFE,
    WEAPON_METAL_ROD,
    WEAPON_CROSSBOW,
    WEAPON_CHAINSAW,
    ACCESSORY_NECKLACE,
    ACCESSORY_BANGLE,
    ACCESSORY_RING,
    ACCESSORY_TALISMAN,
    COSTUME,
    ATTACHMENT_1,
    AGITATION_LOOP,
    DUMMY,
    CURRENCY,
};

