#pragma once
#include "CoreMinimal.h"
#include "EManagerTypeID.generated.h"

UENUM(BlueprintType)
enum class EManagerTypeID : uint8 {
    RenderTarget,
    Input,
    Resource,
    Scene,
    Level,
    PostProcess,
    ParallelObject,
    Database,
    AddContentManager,
    AnimeInterlockingManager,
    Achievement,
    RSAccountManager,
    Sound,
    ParticleSystem,
    Movie,
    MessageHud,
    UserParam,
    Flag,
    Event,
    Player,
    Hit,
    BrainCrash,
    SAS,
    PsychicObject,
    BlendableVolume,
    Enemy,
    BrainField,
    RadialBlur,
    Bsp,
    Battle,
    Battlefield,
    Stage,
    Action,
    BrainTalk,
    ArrangeItem,
    DropItem,
    GameMain,
    GameSystem,
    SaveLoadParamClass,
    InGameFlow,
    FinishManager,
    MapGimmick,
    LC21MapGimmick,
    CosmosWeb,
    TriggerEffect,
    ActivityManager,
    XGameStreaming,
    BattleSimulator,
    ClearGetter,
    ShareUtilityManager,
    TwoShotParam,
    Num,
};

