#pragma once
#include "CoreMinimal.h"
#include "EMapGimmickType.generated.h"

UENUM(BlueprintType)
enum class EMapGimmickType : uint8 {
    MGIMMICKTYPE_UNKNOWN,
    MGIMMICKTYPE_HANGED_RESOURCE,
    MGIMMICKTYPE_TRAIN,
    MGIMMICKTYPE_HOOK,
    MGIMMICKTYPE_HIGHWAY_FENCE,
    MGIMMICKTYPE_TANKLORRY,
    MGIMMICKTYPE_BELTCONVEYOR,
    MGIMMICKTYPE_MOVABLEBRIDGE,
    MGIMMICKTYPE_TELEPORTWALL,
    MGIMMICKTYPE_CAMERAGATE,
    MGIMMICKTYPE_GATE,
    MGIMMICKTYPE_CONSOLE,
    MGIMMICKTYPE_LASERGATE,
    MGIMMICKTYPE_STEELMESH,
    MGIMMICKTYPE_CARDDOOR,
    MGIMMICKTYPE_STEAMPIPE,
    MGIMMICKTYPE_BIGICE,
    MGIMMICKTYPE_BIGICEOBJECT,
    MGIMMICKTYPE_PSYCHICMOVEROAD,
    MGIMMICKTYPE_SWITCHBOARD,
    MGIMMICKTYPE_SWITCHBOARDGATE,
    MGIMMICKTYPE_TRANSFORMER,
    MGIMMICKTYPE_DUMPCAR,
    MGIMMICKTYPE_SIMPLEGATE,
    MGIMMICKTYPE_OBSERVATOR,
    MGIMMICKTYPE_ELECTRICLOCK,
    MGIMMICKTYPE_BIGICE_ATTACK,
    Num,
};

