#pragma once
#include "CoreMinimal.h"
#include "EMeansOfKillType.generated.h"

UENUM(BlueprintType)
enum class EMeansOfKillType : uint8 {
    Invalid,
    Attack_Weapon,
    Attack_Charge,
    Attack_Air,
    Attack_Assassin,
    Attack_Psychic,
    Attack_PsyCombo,
    Attack_BrainCrash,
    Attack_BrainCrashMulti,
    Attack_Drive,
    Attack_BrainField,
    Attack_JustDodgeAttack,
    Attack_JustDodgePsychic,
    Attack_PsychicField,
    Attack_PsychicObjectDropAttack,
    Attack_Intercept,
    SpecialOBJ_All,
    SpecialOBJ_ElectricPole,
    SpecialOBJ_VendingMachine,
    SpecialOBJ_SteelBeams,
    SpecialOBJ_TankSet,
    SpecialOBJ_Fence,
    SpecialOBJ_Drone,
    SpecialOBJ_Container,
    SpecialOBJ_Vehicle,
    SpecialOBJ_Pillar,
    SpecialOBJ_Statue,
    SpecialOBJ_Bulldozer,
    SpecialOBJ_DuelPole,
    SpecialOBJ_FloorFragment,
    SpecialOBJ_Cube,
    SpecialOBJ_Rock,
    SpecialOBJ_ElectronicParts,
    SpecialOBJ_Chandelier,
    SpecialOBJ_IronRailing,
    SpecialOBJ_DimensionEntanglement,
    SAS_All,
    SAS_Fire,
    SAS_Electric,
    SAS_Telepo,
    SAS_Accelerator,
    SAS_Metal,
    SAS_Stealth,
    SAS_SeeThrough,
    SAS_Copy,
    SAS_Psychic,
    Attack_FallAttack,
    CombiVision_All,
    CombiVision_Fire,
    CombiVision_Electric,
    CombiVision_Telepo,
    CombiVision_Accelerator,
    CombiVision_Metal,
    CombiVision_Stealth,
    CombiVision_SeeThrough,
    CombiVision_Copy,
    CombiVision_Psychic,
};

