#pragma once
#include "CoreMinimal.h"
#include "ENpcAnimationKind.generated.h"

UENUM(BlueprintType)
enum class ENpcAnimationKind : uint8 {
    NPCANIM_IDLE,
    NPCANIM_WALK,
    NPCANIM_RUN,
    NPCANIM_JOY,
    NPCANIM_SCARED,
    NPCANIM_SITDOWN,
    NPCANIM_ANIMEX1,
    NPCANIM_ANIMEX2,
    NPCANIM_ANIMEX3,
    NPCANIM_ANIMEX4,
    NPCANIM_ANIMEX5,
    NPCANIM_ANIMEX6,
    NPCANIM_ANIMEX7,
    NPCANIM_ANIMEX8,
    NPCANIM_ANIMEX9,
    NPCANIM_ANIMEX10,
    NPCANIM_AJITO01,
    NPCANIM_AJITO02,
    NPCANIM_AJITO03,
    NPCANIM_AJITO04,
    NPCANIM_AJITO05,
    NPCANIM_AJITO06,
    NPCANIM_AJITO07,
    NPCANIM_AJITO08,
    NPCANIM_AJITO09,
    NPCANIM_AJITO10,
    NPCANIM_NUM,
    NPCANIM_MAX UMETA(Hidden),
};

