#pragma once
#include "CoreMinimal.h"
#include "EPlayerAIBattleThinkTransitionCPP.generated.h"

UENUM(BlueprintType)
enum class EPlayerAIBattleThinkTransitionCPP : uint8 {
    None,
    TargetDistNear,
    TargetDistMiddle,
    TargetDistFar,
    TargetDistTooFar,
    TargetDamageWince,
    AttackHit,
    NotTargetActionAttack,
    TargetActionAttack,
    AttachAbleCH1000,
    HardenMode,
    Targeted,
    NotTargeted,
    FogApply,
    IsENpcBarrier,
    CanSpecialMoveTrigger,
    TargetDamageDown,
    CommonBranchNone,
    CommonBranch1,
    CommonBranch2,
    TargetDir4Front,
    TargetDir4Back,
    ChangeBrainField,
    CaptureAble,
    TargetFloating,
    UnderSiege,
    ControlPlayerStealth,
    EnableSeeThrough,
    DriveMode,
    LevelLearnAttack,
    InterruptAction,
    Stealth,
    FinishMetamorphosis,
    ThinkPhaseTransition0,
    ThinkPhaseTransition1,
    ThinkPhaseTransition2,
    ThinkPhaseTransition3,
    UniqueCondition0,
    UniqueCondition1,
    UniqueCondition2,
    UniqueCondition3,
    EnableCreateCopy,
    NotPlayerBrainField,
    NearDeadNpc,
    FarDeadNpc,
    EnableDrive,
    EnableRegistSAS,
    SasFire,
    SasElectric,
    SasTeleport,
    InScreen,
    TargetCanBeAttacked,
    StartBattleTimer,
    TargetNotStealth,
};

