#pragma once
#include "CoreMinimal.h"
#include "EPlayerHitStopType.generated.h"

UENUM(BlueprintType)
enum class EPlayerHitStopType : uint8 {
    NormalAttack,
    WeakMaterialChange,
    EnemyBadStatus,
    BrainCrashTrigger,
    ArmorBreak,
    PlayerBadStatus,
    PsychicObjectAttack,
    DelayDead,
    WeakExPsychic,
    ExPsychic,
    EnemyDeadNormalAttack,
    EnemyDeadPsychicAttack,
    UniqueObject,
    EnablePsychicAttack,
    EnableNormalAttack,
    ComboPsychicAttack,
    DirectShot,
    InterceptAttack,
    EnemyUniqueAttack,
    EnemyDownAttack,
    EnemyReactionLAttack,
    EnemyBlowAttack,
    EnemyAddDamageAttack,
    EnemyDownPsychicAttack,
    EnemyReactionLPsychicAttack,
    ENPCUniqueReactionAttack,
    ENPCReactionSAttack,
    ENPCNormalAttack,
    ENPCSpTriggerAttack,
    SlamPsychicAttack,
    BrainfieldDropPsychicAttack,
    StealthCritical,
    FullInactiveWeak,
    DropMapGimmick,
    DumpCarMapGimmick,
    HookMapGimmick,
    HookSecondHitMapGimmick,
    TrainMapGimmick,
    TrainSecondHitMapGimmick,
    TankLorryMapGimmick,
    ScalptureMapGimmick,
    TransformerHitMapGimmick,
    CeilingScaffoldMapGimmick,
    AssassinAttack,
    NexusDriveTelepoAttack,
    NexusDriveChargeTelepoAttack,
};

