#pragma once
#include "CoreMinimal.h"
#include "EPlayerCameraPreset.generated.h"

UENUM(BlueprintType)
enum class EPlayerCameraPreset : uint8 {
    Default,
    Outdoor,
    Indoor,
    AssemblyRoom,
    Elevator,
    BrainField,
    LC22_Default,
    LC22_Indoor,
    LC22_Outdoor,
    LC56_Default,
    LC56_Outdoor,
    UniqueObjectDrone,
    UniqueObjectFence,
    em1300_in,
    em1300_out,
    em03xx_out,
    ENPC_Default_1,
    ENPC_Default_2,
    ENPC_Default_3,
    ENPC_AnimeKaren,
    Mg_Transformer,
    Mg_DumpCar,
    Mg_CeilingScaffold,
    PlayerCameraPreset13,
    PlayerCameraPreset14,
    PlayerCameraPreset15,
    PlayerCameraPreset16,
    PlayerCameraPreset17,
    PlayerCameraPreset18,
    PlayerCameraPreset19,
    PlayerCameraPreset20,
    PlayerCameraPreset21,
    PlayerCameraPreset22,
    PlayerCameraPreset23,
    PlayerCameraPreset24,
    PlayerCameraPreset25,
    PlayerCameraPreset26,
    PlayerCameraPreset27,
    PlayerCameraPreset28,
    PlayerCameraPreset29,
    PlayerCameraPreset30,
    em03xx_ceiling,
    UniqueObjectDrone_Attack,
    DefaultNew,
    OutdoorNew,
    IndoorNew,
    Max,
};

