#pragma once
#include "CoreMinimal.h"
#include "EPlayerAIBattleThinkTypeCPP.generated.h"

UENUM(BlueprintType)
enum class EPlayerAIBattleThinkTypeCPP : uint8 {
    MainThink_Move,
    MainThink_AttackNear,
    MainThink_AttackMiddle,
    MainThink_AttackFar,
    MainThink_Other,
    SubThink_Move_Near,
    SubThink_Move_Middle,
    SubThink_Move_Far,
    SubThink_Other_MoveCircle,
    SubThink_Other_MoveRandom,
    SubThink_Dodge,
    SubThink_Attack1,
    SubThink_Attack2,
    SubThink_Attack3,
    SubThink_Attack4,
    SubThink_Attack5,
    SubThink_Attack6,
    SubThink_Attack7,
    SubThink_Attack8,
    SubThink_Attack9,
    SubThink_Attack10,
    SubThink_Attack11,
    SubThink_Attack12,
    SubThink_Attack13,
    SubThink_Attack14,
    SubThink_Attack15,
    SubThink_Attack16,
    SubThink_Attack17,
    SubThink_Attack18,
    SubThink_Attack19,
    SubThink_Attack20,
    SubThink_Attack_Chain1,
    SubThink_UseItem,
    SubThink_Revival,
    SubThink_Special_EndAttackTelepo,
    SubThink_Wait,
    SubThink_MoveAttack,
    SubThink_MoveAim,
    SubThink_RushAttack,
    SubThink_EscapeKeepOutArea,
    SubThink_Caution,
    SubThink_Psychic,
    SubThink_PsychicCombo,
    SubThink_PsychicCombo2,
    SubThink_BattleStart,
    SubThink_SeeThrough,
    SubThink_Intercept,
    SubThink_CautionAttack,
    SubThink_ReviveNpc,
    SubThink_EnpcDrive,
    Num,
};

