#pragma once
#include "CoreMinimal.h"
#include "ESASEffect.generated.h"

UENUM(BlueprintType)
enum class ESASEffect : uint8 {
    RecastSec,
    ActivationSec,
    HologramSkill,
    CoverDamage,
    WeaponElectric,
    ObjectElectric,
    ElectricSkillCharge,
    ElectricSkillDome,
    ReinforceElectric,
    GuardElectric,
    WeaponFire,
    ObjectFire,
    FireSkillPiller,
    FireSkillThrower,
    ReinforceFire,
    GuardFire,
    Accelerate_LV1,
    FastItem,
    AccelerateRecover,
    DodgeTelepo,
    DodgeTelepoAir,
    AttackTelepo,
    ChargeTelepo,
    Metal,
    BadStatusGuard,
    AutoGuard,
    SeeThrough,
    EaseJustDodge,
    JustDodgeAttackDown,
    LargeCaptureArea,
    BrainCrashUp,
    DropUp,
    JustDodgeAttack,
    JustDodgePsychic,
    JustDodgeArmorBreak,
    Stealth,
    AssassinAttack,
    AutoStealth,
    ExtendStealth,
    ExtendStealthLong,
    ArmorBreakAssassinAttack,
    ObjectCopy,
    ObjectCopy2,
    SelfCopy,
    SelfCopy2,
    PsychicCostZero,
    PsychicField_LV1,
    PsychicField_LV2,
    Intercept,
    None,
};

