#pragma once
#include "CoreMinimal.h"
#include "EUIViewPrio.generated.h"

UENUM(BlueprintType)
enum class EUIViewPrio : uint8 {
    None = 0xFF,
    ActionIcon_Etc = 0x0,
    ActionIcon_SubQuest,
    ActionIcon_Resurrection,
    ActionIcon_MainTalk,
    ActionIcon_Prio,
    AreaNextName,
    DiscoverIcon,
    WeightGauge_Normal,
    WeightGauge_Strength,
    WeightGauge_Prio,
    Fade1,
    Movie,
    Telop,
    MapGimmick,
    MapGimmick_Prio,
    EnemyVitality,
    Crashtrigger,
    StaffRoll,
    GameOver,
    MessageLog,
    NoticeMessage,
    BrainTalk,
    TutoOperation,
    BattleControl,
    Code,
    Keyword,
    VisionSimulatorSelect,
    VisionSimulatorStartEnd,
    VisionSimulatorResult,
    TitleLogoMenu,
    TitleMenu,
    CharaSelectMenu,
    TitleCrossSave,
    MainMenu,
    DetailMapMenu,
    WorldMapMenu,
    ShopMenu,
    ShopWeaponMenu,
    ShopEnemyBooks,
    Present,
    PresentNext,
    SaveLoadMenu,
    NoticeQuest,
    AutoSave,
    VisionSimulator,
    ScarletLogo,
    LicensePopMenu,
    FirstLanguagePopMenu,
    FirstConfirmPopMenu,
    Fade2,
    LoadingLow,
    LoadingHigh,
    TitleMovie,
    TelopEventTitle,
    FadeEventTitle,
    PhotoMode,
    HelpTutoMenu,
    SystemMessage,
    GeneralMenu,
    SystemNoticeMenu,
    LetterBoxMask,
    Num,
    EUIViewPrio_MAX,
};

